version: 2.1

orbs:
  ruby: circleci/ruby@2.0.0

jobs:
  rubocop:
    docker:
      - image: cimg/ruby:3.1.2
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check:
          format: progress
          label: Inspecting with Rubocop
  test:
    docker:
      - image: cimg/ruby:3.1.2
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test:
          include: spec/**/*_spec.rb
  bearer:
    docker:
      - image: cimg/ruby:3.2
    environment:
      # Set to default branch of your repo
      DEFAULT_BRANCH: main
    steps:
      - checkout
      - run: curl -sfL https://raw.githubusercontent.com/Bearer/bearer/main/contrib/install.sh | sh -s -- -b /tmp
      - run: CURRENT_BRANCH=$CIRCLE_BRANCH SHA=$CIRCLE_SHA1 /tmp/bearer scan .
workflows:
  build_and_test:
    jobs:
      - rubocop
      - test
      - bearer
