version: 2.1

orbs:
  ruby: circleci/ruby@2.5.2
  coveralls: coveralls/coveralls@2.2.5

jobs:
  rubocop:
    docker:
      - image: cimg/ruby:3.4.1
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check:
          format: progress
          label: Inspecting with Rubocop
  test:
    docker:
      - image: cimg/ruby:3.4.1-node
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test:
          include: spec/**/*_spec.rb
      - coveralls/upload:
          coverage_file: ./coverage/lcov/project.lcov
  bearer:
    docker:
      - image: cimg/ruby:3.4.1
    environment:
      # Set to default branch of your repo
      DEFAULT_BRANCH: main
    steps:
      - checkout
      - run: curl -sfL https://raw.githubusercontent.com/Bearer/bearer/main/contrib/install.sh | sh -s -- -b /tmp
      - run: CURRENT_BRANCH=$CIRCLE_BRANCH SHA=$CIRCLE_SHA1 /tmp/bearer scan .
  semgrep:
    docker:
        - image: returntocorp/semgrep
    steps:
      - checkout
      - run:
          name: Check code against community-provided and custom semgrep rules
          command: semgrep ci --config auto
workflows:
  build_and_test:
    jobs:
      - rubocop
      - test
      - bearer
      - semgrep
